apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: monitoring
data:
  METRICS_ADDR: "0.0.0.0"
  METRICS_PORT: "55555"
  DELAY: "0.1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: monitoring
spec:
  replicas: 4
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: frossrunner/collector-exporter:latest
        ports:
        - containerPort: 8000
        env:
        - name: METRICS_ADDR
          valueFrom:
            configMapKeyRef:
              name: collector-config
              key: METRICS_ADDR
        - name: METRICS_PORT
          valueFrom:
            configMapKeyRef:
              name: collector-config
              key: METRICS_PORT
        - name: CELL_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CELL_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: collector
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30800

