{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Active Cell Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.component == \"du\")\r\n  |> filter(fn: (r) => r._field == \"active_cells_count\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "CU Moving Average Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.component == \"cu_up\")\r\n  |> filter(fn: (r) => r._measurement == \"cu_up_pdcp_statistics\")\r\n  |> filter(fn: (r) => r._field == \"average_throughput_Mbps_moving_average\")\r\n  |> group(columns: [\"direction\"])\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active UE Count",
   "type": "stat",
   "description": "imeisv tracking",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.component == \"cell\")\r\n  |> filter(fn: (r) => r._field == \"active_ue_count_imeisv\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Per UE Cqi",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 7, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.component == \"cell\")\r\n  |> filter(fn: (r) => r._measurement == \"ue_metrics\")\r\n  |> filter(fn: (r) => r._field == \"cqi\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Memory Usage MB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.component == \"app_monitor\")\r\n  |> filter(fn: (r) => r._measurement == \"app_resource_usage\")\r\n  |> filter(fn: (r) => r._field == \"memory_usage_MB\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Event Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.component == \"cell\")\r\n  |> filter(fn: (r) => r._field == \"event_count\")\r\n  |> group(columns: [\"event_type\"])\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "per UE SNR",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 7, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.component == \"cell\")\r\n  |> filter(fn: (r) => r._measurement == \"ue_metrics\")\r\n  |> filter(fn: (r) => r._field == \"pusch_snr_db\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Cpu Usage Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.component == \"app_monitor\")\r\n  |> filter(fn: (r) => r._measurement == \"app_resource_usage\")\r\n  |> filter(fn: (r) => r._field == \"cpu_usage_percent\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: true)"
    }
   ]
  }
 ]
}