apiVersion: v1
kind: ConfigMap
metadata:
  name: core-collector-config
  namespace: monitoring
data:
  INFLUXDB_URL: 'http://10.233.52.119:80'
  INFLUXDB_TOKEN: 'my-super-secret-token'
  INFLUXDB_ORG: 'influxdata'
  INFLUXDB_BUCKET: 'metrics'
  SCRAPE_INTERVAL: '0.1'
  SCRAPE_TIMEOUT: '1'
  ENDPOINTS:
    - name: upf
      url: http://10.0.0.1:9097/metrics?fallback_scrape_protocol=text/plain
      component: upf

    - name: pcf
      url: http://10.0.0.1:9103/metrics
      component: pcf

    - name: amf
      url: http://10.0.0.1:9095/metrics
      component: amf

    - name: smf
      url: http://10.0.0.1:9094/metrics
      component: smf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-collector
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-collector
  template:
    metadata:
      labels:
        app: core-collector
    spec:
      containers:
      - name: core-collector
        image: frossrunner/core-collector:latest
        command:
          - sleep
          - inf
        env:
        - name: TARGET_PORT
          valueFrom:
            configMapKeyRef:
              name: core-collector-config
              key: TARGET_PORT
        - name: TARGET_IP
          valueFrom:
            configMapKeyRef:
              name: core-collector-config
              key: TARGET_IP
        - name: DELAY
          valueFrom:
            configMapKeyRef:
              name: core-collector-config
              key: DELAY
        - name: ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: core-collector-config
              key: ENDPOINTS